import React, { useState } from "react";
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, SafeAreaView } from "react-native";
import { Package, UtensilsCrossed, Wrench, Car, Clock } from "lucide-react-native";
import { COLORS } from "../theme/colors";
const tabs = ["All", "Orders", "Services", "Rides"];
const activity = [
  { icon: Package, title: "Chuka's Provisions Store", detail: "3 items · ₦12,700", status: "On the way", statusType: "active", time: "Today, 2:14pm", type: "Orders" },
  { icon: Wrench, title: "Tunde Electricals", detail: "Wiring repair · ₦3,500", status: "Completed", statusType: "done", time: "Yesterday, 5:40pm", type: "Services" },
  { icon: UtensilsCrossed, title: "Mama Nkechi Kitchen", detail: "Jollof rice combo · ₦4,200", status: "Completed", statusType: "done", time: "Mon, 1:10pm", type: "Orders" },
  { icon: Car, title: "Ride to Ikeja", detail: "Yaba → Ikeja · ₦2,100", status: "Completed", statusType: "done", time: "Sun, 8:02am", type: "Rides" },
  { icon: Wrench, title: "QuickFix Plumbing", detail: "Pipe leak fix · Pending", status: "Pending", statusType: "pending", time: "Sun, 6:30am", type: "Services" },
];
const statusColor = { active: { bg: "#FDEDE1", fg: COLORS.amber }, done: { bg: "#E1F0EA", fg: COLORS.teal }, pending: { bg: "#F1E9D9", fg: "#9A7B2E" } };
export default function ActivityScreen() {
  const [activeTab, setActiveTab] = useState("All");
  const filtered = activeTab === "All" ? activity : activity.filter((a) => a.type === activeTab);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.headerTitle}>My Activity</Text></View><View style={styles.tabsWrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{tabs.map((t) => { const active = t === activeTab; return <TouchableOpacity key={t} style={[styles.tabChip, { backgroundColor: active ? COLORS.teal : COLORS.card, borderWidth: active ? 0 : 1 }]} onPress={() => setActiveTab(t)}><Text style={[styles.tabChipText, { color: active ? "#fff" : COLORS.inkSoft }]}>{t}</Text></TouchableOpacity>; })}</ScrollView></View><ScrollView style={{ flex: 1 }} contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 24, gap: 10 }}>{filtered.map((a, i) => { const sc = statusColor[a.statusType]; const Icon = a.icon; return <View key={i} style={styles.activityCard}><View style={styles.activityIconWrap}><Icon size={18} color={COLORS.teal} /></View><View style={{ flex: 1 }}><Text style={styles.activityTitle}>{a.title}</Text><Text style={styles.activityDetail}>{a.detail}</Text><View style={styles.activityBottomRow}><View style={styles.activityTimeRow}><Clock size={10} color={COLORS.inkSoft} /><Text style={styles.activityTime}>{a.time}</Text></View><View style={[styles.statusBadge, { backgroundColor: sc.bg }]}><Text style={[styles.statusText, { color: sc.fg }]}>{a.status}</Text></View></View></View></View>; })}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.bg }, header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 16 }, headerTitle: { color: COLORS.ink, fontFamily: "Manrope_800ExtraBold", fontSize: 20 }, tabsWrap: { paddingHorizontal: 20, marginBottom: 16 }, tabChip: { borderRadius: 999, borderColor: COLORS.line, paddingHorizontal: 14, paddingVertical: 8 }, tabChipText: { fontSize: 12, fontFamily: "Inter_600SemiBold" }, activityCard: { backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.line, borderRadius: 16, padding: 14, flexDirection: "row", gap: 12 }, activityIconWrap: { width: 42, height: 42, borderRadius: 12, backgroundColor: COLORS.amberSoft, alignItems: "center", justifyContent: "center" }, activityTitle: { color: COLORS.ink, fontFamily: "Inter_600SemiBold", fontSize: 13 }, activityDetail: { color: COLORS.inkSoft, fontSize: 11.5, marginTop: 2, fontFamily: "Inter_400Regular" }, activityBottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10 }, activityTimeRow: { flexDirection: "row", alignItems: "center", gap: 4 }, activityTime: { fontSize: 10.5, color: COLORS.inkSoft, fontFamily: "Inter_400Regular" }, statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 }, statusText: { fontSize: 10.5, fontFamily: "Inter_600SemiBold" } });
